import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

DARK_BLUE = colors.HexColor("#1e3a5f")
LIGHT_GRAY = colors.HexColor("#f5f5f5")


def generate_invoice_pdf(invoice_data: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )
    elements = []
    styles = getSampleStyleSheet()
    inv_date = invoice_data.get("date") or datetime.now().strftime("%Y-%m-%d")

    header_data = [
        [
            Paragraph(
                f"<b>{invoice_data['business_name']}</b>",
                ParagraphStyle("biz", fontSize=18, textColor=DARK_BLUE),
            ),
            Paragraph(
                "<b>INVOICE</b>",
                ParagraphStyle("inv", fontSize=24, textColor=DARK_BLUE, alignment=TA_RIGHT),
            ),
        ],
        [
            Paragraph(f"📞 {invoice_data.get('business_phone', '')}", styles["Normal"]),
            Paragraph(
                f"#{invoice_data['invoice_number']}<br/>{inv_date}",
                ParagraphStyle("num", alignment=TA_RIGHT),
            ),
        ],
    ]
    header_table = Table(header_data, colWidths=[10 * cm, 7 * cm])
    elements.append(header_table)
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph("Bill To:", ParagraphStyle("to", fontSize=10, textColor=colors.gray)))
    elements.append(
        Paragraph(
            f"<b>{invoice_data['customer_name']}</b>",
            ParagraphStyle("cust", fontSize=14),
        )
    )
    elements.append(Spacer(1, 0.5 * cm))

    table_data = [["Item", "Qty", "Unit Price", "Total"]]
    subtotal = 0.0
    for item in invoice_data["items"]:
        total = float(item["qty"]) * float(item["price"])
        subtotal += total
        table_data.append(
            [
                item["name"],
                str(item["qty"]),
                f"Rs. {float(item['price']):,.0f}",
                f"Rs. {total:,.0f}",
            ]
        )
    table_data.append(["", "", "TOTAL", f"Rs. {subtotal:,.0f}"])

    items_table = Table(table_data, colWidths=[9 * cm, 2 * cm, 3 * cm, 3 * cm])
    items_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), DARK_BLUE),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, LIGHT_GRAY]),
                ("BACKGROUND", (0, -1), (-1, -1), DARK_BLUE),
                ("TEXTCOLOR", (0, -1), (-1, -1), colors.white),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                ("GRID", (0, 0), (-1, -2), 0.5, colors.lightgrey),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(items_table)
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(
        Paragraph(
            f"💳 Payment Method: {invoice_data.get('payment_method', 'Cash')}",
            styles["Normal"],
        )
    )
    elements.append(Spacer(1, 1 * cm))
    elements.append(
        Paragraph(
            "Generated by HisaabAI — aapka digital munshi 🤝",
            ParagraphStyle("footer", fontSize=9, textColor=colors.gray, alignment=TA_CENTER),
        )
    )
    doc.build(elements)
    return buffer.getvalue()
